### ISSUE TITLE
Similar module/configuration for Apache?

### ISSUE THREAD

**Issue by nodiscc** [nulab/nginx-length-hiding-filter-module#2]
Asking here because I really don't know better.

I would like to hide response length on my apache 2.4 server setup. Do you know an apache module or configuration switch that offers functionality similar to this nginx module?

Any help is welcome, thanks in advance.

**Comment by tksmd** [comment]
@nodiscc I'm sorry but I don't know apache module equivalent to this nginx module. I'm not sure of its performance overhead though you may be able to do the same thing using mod_ext_filter.
- http://httpd.apache.org/docs/2.4/mod/mod_ext_filter.html 

If you're familiar with Perl, writing filter using mod_perl might be easier and simpler than writing apache module in standard C style.
- https://perl.apache.org/docs/2.0/user/handlers/filters.html#Output_Filters

HTH

**Comment by tksmd** [comment]
It's not an actual issue so closed. If you have further questions, kindly add comment here.
