### ISSUE TITLE
Filter not applied to http 403 pages that return content

### ISSUE THREAD

**Issue by rcpeters** [nulab/nginx-length-hiding-filter-module#7]
Great module, but we've noticed an issue.

We are proxying a CMS. When the CMS receives a request to a protected resource it returns a http 403 code w/html content.

Page where filter is applied:
https://qa.orcid.org

Page where filter isn't applied:
https://qa.orcid.org/admin/randompage

**Comment by dragon3** [comment]
Hi @rcpeters ,
Can you please try `enable-all-response-except-for-no-content` branch which enables this filter on all HTTP response statuses except for No Content (204)?

**Comment by rcpeters** [comment]
@jpeerz can you test. See above.

**Comment by dragon3** [comment]
Hi @rcpeters  and @jpeerz 
Please let me know if you try the branch and it works properly.

I've confirmed it works on our testing environment, so I'm going to release new version soon.

Thank you!

**Comment by jpeerz** [comment]
Thanks for your fast turn around @dragon3

I'm currently rebuilding nginx for versions 1.4.6 and 1.10.0.

I'll let you know my results as soon I get both instances running with your patch.

**Comment by dragon3** [comment]
I've released the new version [1.1.1](https://github.com/nulab/nginx-length-hiding-filter-module/releases/tag/1.1.1) , so I'm going to close this issue.

Hi @rcpeters and @jpeerz ,
Please let me know if you still have the problem, and also please make sure that version (1.1.1) only support nginx-1.10.1 or later.

Thank you!
